name: getting_started
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - matplotlib
  - pip:
    - adlfs
    - azure-storage-file-datalake
    - azure-identity
    - connectorx
    - dbt-duckdb
    - duckdb-engine
    - jupysql
    - mkdocs
    - mkdocs-autorefs
    - mkdocs-glightbox
    - mkdocs-material
    - mkdocs-material-extensions
    - mkdocstrings
    - mkdocstrings-python
    - mypy
    - oracledb
    - pandas[performance, fsspec, pyarrow, clipboard] >=2.0.0
    - piperider[duckdb]
    - polars[all]
    - pre-commit
    - ruff
    - sqlalchemy >=2.0.0
    - sqlfluff
    - sqlfluff-templater-dbt
    - streamlit
    - xlsxwriter


