site_name: Skuld Reinsurance
site_url: https://profisee.skuld.com/riskanalytics/reinsurance
site_author: Risk Analytics

nav:
    - Home: 'index.md'
    - Architecture: 
      - architecture/overview.md
      - architecture/knowledge.md
    - 'Technical guides':
      - technical/learn_mkdocs.md
    - Dataflows: static/dbt/index.html

theme:
  name: "material"
  logo: assets/skuld_logo.png
  favicon: assets/logo.jpg
  features:
    - navigation.footer

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - glightbox

watch:
 - README.md
